### ISSUE TITLE
Crear SQL de INSERT

### ISSUE THREAD

**Issue by xmarchena50072-ufide** [xmarchena50072-ufide/Proyecto-SC-504#1]
Agregar cambios al archivo Inventario.sql

**Comment by josh030310** [comment]
-- Inserciones en la tabla "CATEGORIAS"
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (3, 'Categoría 3');

INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (4, 'Categoría 4');

-- Inserciones en la tabla "EQUIPOS"
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUM_SERIE, CANTIDAD_DISPONIBLE, CATEGORIA)
VALUES (1, 'Equipo 1', 'Descripción del Equipo 1', 'NS001', 10, 1);

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUM_SERIE, CANTIDAD_DISPONIBLE, CATEGORIA)
VALUES (2, 'Equipo 2', 'Descripción del Equipo 2', 'NS002', 5, 2);

-- Inserciones en la tabla "DEPARTAMENTOS"
INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO)
VALUES (1, 'Departamento 1');

INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO)
VALUES (2, 'Departamento 2');

-- Inserciones en la tabla "PERSONAL"
INSERT INTO PERSONAL (ID_PERSONAL, NOMBRE, TELEFONO, CORREO, ID_DEPARTAMENTO)
VALUES (1, 'Persona 1', '123456789', 'persona1@example.com', 1);

INSERT INTO PERSONAL (ID_PERSONAL, NOMBRE, TELEFONO, CORREO, ID_DEPARTAMENTO)
VALUES (2, 'Persona 2', '987654321', 'persona2@example.com', 2);

-- Inserciones en la tabla "ROLES"
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION)
VALUES (1, 'Rol 1', 'Descripción del Rol 1');

INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION)
VALUES (2, 'Rol 2', 'Descripción del Rol 2');

-- Inserciones en la tabla "PERMISOS"
INSERT INTO PERMISOS (ID_PERMISOS, NOMBRE, ID_ROL, DESCRIPCION)
VALUES (1, 'Permiso 1', 1, 'Descripción del Permiso 1');

INSERT INTO PERMISOS (ID_PERMISOS, NOMBRE, ID_ROL, DESCRIPCION)
VALUES (2, 'Permiso 2', 2, 'Descripción del Permiso 2');

-- Inserciones en la tabla "PROVEEDORES"
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE, TELEFONO, CORREO)
VALUES (1, 'Proveedor 1', '555-123456', 'proveedor1@example.com');

INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE, TELEFONO, CORREO)
VALUES (2, 'Proveedor 2', '555-987654', 'proveedor2@example.com');

-- Inserciones en la tabla "RECEPCIONES"
INSERT INTO RECEPCIONES (ID_RECEPCION, ID_EQUIPO, ID_ALMACEN, FECHA, HORA)
VALUES (1, 1, 1, CURRENT_DATE, CURRENT_TIMESTAMP);

INSERT INTO RECEPCIONES (ID_RECEPCION, ID_EQUIPO, ID_ALMACEN, FECHA, HORA)
VALUES (2, 2, 2, CURRENT_DATE, CURRENT_TIMESTAMP);

-- Inserciones en la tabla "ALMACENES"
INSERT INTO ALMACENES (ID_ALMACEN, ID_RECEPCION, ID_EQUIPO, NOMBRE_ALMACEN)
VALUES (1, 1, 1, 'Almacén 1');

INSERT INTO ALMACENES (ID_ALMACEN, ID_RECEPCION, ID_EQUIPO, NOMBRE_ALMACEN)
VALUES (2, 2, 2, 'Almacén 2');

-- Inserciones en la tabla "DESPACHOS"
INSERT INTO DESPACHOS (ID_DESPACHO, ID_EQUIPO, ID_DEPARTAMENTO, FECHA, HORA, ID_PERSONAL)
VALUES (1, 1, 1, CURRENT_DATE, CURRENT_TIMESTAMP, 1);

INSERT INTO DESPACHOS (ID_DESPACHO, ID_EQUIPO, ID_DEPARTAMENTO, FECHA, HORA, ID_PERSONAL)
VALUES (2, 2, 2, CURRENT_DATE, CURRENT_TIMESTAMP, 2);

-- Inserciones en la tabla "USUARIOS"
INSERT INTO USUARIOS (ID_USUARIOS, ID_PERSONAL, USERNAME, PASSWORD, ID_ROL)
VALUES (1, 1, 'usuario1', 'contraseña1', 1);

INSERT INTO USUARIOS (ID_USUARIOS, ID_PERSONAL, USERNAME, PASSWORD, ID_ROL)
VALUES (2, 2, 'usuario2', 'contraseña2', 2);

-- Inserciones en la tabla "COMPRA"
INSERT INTO COMPRA (ID_COMPRA, ID_PROVEEDOR, FECHA_COMPRA, ID_DETALLE_COMPRA)
VALUES (1, 1, CURRENT_DATE, 1);

INSERT INTO COMPRA (ID_COMPRA, ID_PROVEEDOR, FECHA_COMPRA, ID_DETALLE_COMPRA)
VALUES (2, 2, CURRENT_DATE, 2);

-- Inserciones en la tabla "DETALLE_COMPRA"
INSERT INTO DETALLE_COMPRA (ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 'Material 1', 10, 50.00);

INSERT INTO DETALLE_COMPRA (ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO)
VALUES (2, 'Material 2', 5, 30.00);

**Comment by josh030310** [comment]
-- Inserciones en la tabla "CATEGORIAS"
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (3, 'Categoría 3');

INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (4, 'Categoría 4');

-- Inserciones en la tabla "EQUIPOS"
INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUM_SERIE, CANTIDAD_DISPONIBLE, CATEGORIA)
VALUES (1, 'Equipo 1', 'Descripción del Equipo 1', 'NS001', 10, 1);

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUM_SERIE, CANTIDAD_DISPONIBLE, CATEGORIA)
VALUES (2, 'Equipo 2', 'Descripción del Equipo 2', 'NS002', 5, 2);

-- Inserciones en la tabla "DEPARTAMENTOS"
INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO)
VALUES (1, 'Departamento 1');

INSERT INTO DEPARTAMENTOS (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO)
VALUES (2, 'Departamento 2');

-- Inserciones en la tabla "PERSONAL"
INSERT INTO PERSONAL (ID_PERSONAL, NOMBRE, TELEFONO, CORREO, ID_DEPARTAMENTO)
VALUES (1, 'Persona 1', '123456789', 'persona1@example.com', 1);

INSERT INTO PERSONAL (ID_PERSONAL, NOMBRE, TELEFONO, CORREO, ID_DEPARTAMENTO)
VALUES (2, 'Persona 2', '987654321', 'persona2@example.com', 2);

-- Inserciones en la tabla "ROLES"
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION)
VALUES (1, 'Rol 1', 'Descripción del Rol 1');

INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION)
VALUES (2, 'Rol 2', 'Descripción del Rol 2');

-- Inserciones en la tabla "PERMISOS"
INSERT INTO PERMISOS (ID_PERMISOS, NOMBRE, ID_ROL, DESCRIPCION)
VALUES (1, 'Permiso 1', 1, 'Descripción del Permiso 1');

INSERT INTO PERMISOS (ID_PERMISOS, NOMBRE, ID_ROL, DESCRIPCION)
VALUES (2, 'Permiso 2', 2, 'Descripción del Permiso 2');

-- Inserciones en la tabla "PROVEEDORES"
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE, TELEFONO, CORREO)
VALUES (1, 'Proveedor 1', '555-123456', 'proveedor1@example.com');

INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE, TELEFONO, CORREO)
VALUES (2, 'Proveedor 2', '555-987654', 'proveedor2@example.com');

-- Inserciones en la tabla "RECEPCIONES"
INSERT INTO RECEPCIONES (ID_RECEPCION, ID_EQUIPO, ID_ALMACEN, FECHA, HORA)
VALUES (1, 1, 1, CURRENT_DATE, CURRENT_TIMESTAMP);

INSERT INTO RECEPCIONES (ID_RECEPCION, ID_EQUIPO, ID_ALMACEN, FECHA, HORA)
VALUES (2, 2, 2, CURRENT_DATE, CURRENT_TIMESTAMP);

-- Inserciones en la tabla "ALMACENES"
INSERT INTO ALMACENES (ID_ALMACEN, ID_RECEPCION, ID_EQUIPO, NOMBRE_ALMACEN)
VALUES (1, 1, 1, 'Almacén 1');

INSERT INTO ALMACENES (ID_ALMACEN, ID_RECEPCION, ID_EQUIPO, NOMBRE_ALMACEN)
VALUES (2, 2, 2, 'Almacén 2');

-- Inserciones en la tabla "DESPACHOS"
INSERT INTO DESPACHOS (ID_DESPACHO, ID_EQUIPO, ID_DEPARTAMENTO, FECHA, HORA, ID_PERSONAL)
VALUES (1, 1, 1, CURRENT_DATE, CURRENT_TIMESTAMP, 1);

INSERT INTO DESPACHOS (ID_DESPACHO, ID_EQUIPO, ID_DEPARTAMENTO, FECHA, HORA, ID_PERSONAL)
VALUES (2, 2, 2, CURRENT_DATE, CURRENT_TIMESTAMP, 2);

-- Inserciones en la tabla "USUARIOS"
INSERT INTO USUARIOS (ID_USUARIOS, ID_PERSONAL, USERNAME, PASSWORD, ID_ROL)
VALUES (1, 1, 'usuario1', 'contraseña1', 1);

INSERT INTO USUARIOS (ID_USUARIOS, ID_PERSONAL, USERNAME, PASSWORD, ID_ROL)
VALUES (2, 2, 'usuario2', 'contraseña2', 2);

-- Inserciones en la tabla "COMPRA"
INSERT INTO COMPRA (ID_COMPRA, ID_PROVEEDOR, FECHA_COMPRA, ID_DETALLE_COMPRA)
VALUES (1, 1, CURRENT_DATE, 1);

INSERT INTO COMPRA (ID_COMPRA, ID_PROVEEDOR, FECHA_COMPRA, ID_DETALLE_COMPRA)
VALUES (2, 2, CURRENT_DATE, 2);

-- Inserciones en la tabla "DETALLE_COMPRA"
INSERT INTO DETALLE_COMPRA (ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 'Material 1', 10, 50.00);

INSERT INTO DETALLE_COMPRA (ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO)
VALUES (2, 'Material 2', 5, 30.00);
