### ISSUE TITLE
Usar vistas en procedimientos

### ISSUE THREAD

**Issue by xmarchena50072-ufide** [xmarchena50072-ufide/Proyecto-SC-504#18]
Reemplazar los select from tabla -> select from vista en los procedimientos del package INVENTARIO_MGMT_OBTENER_PKG

**Comment by sheysom15** [comment]
CREATE VIEW
 vista_categorias AS
SELECT ID_CATEGORIA, NOMBRE_CATEGORIA FROM CATEGORIAS;

SELECT*FROM vista_categoria;

CREATE VIEW
 vista_equipo AS
SELECT ID_EQUIPO, NOMBRE_EQUIPO, DESCRIPCION, NUM_SERIE, CANTIDAD_DISPONIBLE, CATEGORIA FROM EQUIPOS;

SELECT*FROM vista_equipo;

CREATE VIEW
 vista_depto AS
SELECT ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO FROM DEPARTAMENTOS;

SELECT*FROM vista_depto;

CREATE VIEW
 vista_personal AS
SELECT ID_PERSONAL, NOMBRE, TELEFONO , CORREO ID_DEPARTAMENTO FROM PERSONAL;

SELECT*FROM vista_personal;


CREATE VIEW
 vista_roles AS
SELECT ID_ROL, NOMBRE, DESCRIPCION FROM ROLES;

SELECT*FROM vista_roles;

CREATE VIEW
 vista_permisos AS
SELECT ID_PERMISOS, NOMBRE, ID_ROL, DESCRIPCION FROM PERMISOS;

SELECT*FROM vista_permisos;

CREATE VIEW
 vista_prove AS
SELECT ID_PROVEEDORES, NOMBRE, TELEFONO, CORREO FROM PROVEEDORES;

SELECT*FROM vista_prove;

CREATE VIEW
 vista_recepciones AS
SELECT ID_RECEPCION, ID_EQUIPO, ID_ALMACEN, FECHA, HORA FROM RECEPCIONES;

SELECT*FROM vista_recepciones;


CREATE VIEW
 vista_almacenes AS
SELECT ID_ALMACEN, ID_RECEPCION, ID_EQUIPO, NOMBRE_ALMACEN FROM ALMACENES;

SELECT*FROM vista_almacenes;


CREATE VIEW
 vista_despachos AS
SELECT ID_DESPACHO, ID_EQUIPO, ID_DEPARTAMENTO, FECHA, HORA, ID_PERSONAL
FROM DESPACHOS;

SELECT*FROM vista_despachos;


CREATE VIEW
 vista_usuario AS
SELECT ID_USUARIO, ID_PERSONAL, USERNAME, PASSWORD, ID_ROL FROM USUARIO;

SELECT*FROM vista_usuario;

CREATE VIEW
 vista_compra AS
SELECT ID_COMPRA, ID_PROVEEDOR, FECHA_COMPRA , ID_DETALLE_COMPRA FROM COMPRA;

SELECT*FROM vista_compra;

CREATE VIEW
 vista_detalles AS
SELECT ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO FROM DETALEES_COMPRA;+ 


SELECT*FROM vista_detalles;
