### ISSUE TITLE
Agregar bloques de exceptions

### ISSUE THREAD

**Issue by xmarchena50072-ufide** [xmarchena50072-ufide/Proyecto-SC-504#33]
Agregar exceptions en procedures de PACKAGE.sql

**Comment by sheysom15** [comment]
CREATE OR REPLACE PROCEDURE obtener_equipos_disponibles(equipos_cursor OUT SYS_REFCURSOR) AS
BEGIN
    BEGIN
   OPEN equipos_cursor FOR
  SELECT *
   FROM equipos
  WHERE cantidad_disponible > 0;
   EXCEPTION
  WHEN OTHERS THEN
           
  DBMS_OUTPUT.PUT_LINE('Error al abrir el cursor: ' || SQLERRM);
          
    END;
END;
/



CREATE OR REPLACE PROCEDURE crear_equipo(
    id_equipo IN INT,
    nombre_equipo IN VARCHAR2,
    descripcion IN VARCHAR2,
    num_serie IN VARCHAR2,
    cantidad_disponible IN INT,
    categoria IN INT
)
AS
BEGIN
 BEGIN
INSERT INTO equipos (id_equipo, nombre_equipo, descripcion, num_serie, cantidad_disponible, categoria
VALUES (id_equipo, nombre_equipo, descripcion, num_serie, cantidad_disponible, categoria);
        
COMMIT;
EXCEPTION
WHEN OTHERS THEN         
ROLLBACK; 
 DBMS_OUTPUT.PUT_LINE('Error al insertar el equipo: ' || SQLERRM);
         
    END;
END;
/


CREATE OR REPLACE PROCEDURE actualizar_equipo(
    id_equipo IN INT,
    nombre_equipo IN VARCHAR2,
    descripcion IN VARCHAR2,
    num_serie IN VARCHAR2,
    cantidad_disponible IN INT,
    categoria IN INT
)
AS
BEGIN
   BEGIN
     UPDATE equipos
    SET nombre_equipo = nombre_equipo,
    descripcion = descripcion,
    num_serie = num_serie,
    cantidad_disponible = cantidad_disponible,
     categoria = categoria
        WHERE id_equipo = id_equipo;
        
     COMMIT;
    EXCEPTION
   WHEN NO_DATA_FOUND THEN
           
  DBMS_OUTPUT.PUT_LINE('No se encontró el equipo con ID ' || id_equipo);
    WHEN OTHERS THEN
           
    ROLLBACK;
   DBMS_OUTPUT.PUT_LINE('Error al actualizar el equipo: ' || SQLERRM);
            
    END;
END;
/




CREATE OR REPLACE PROCEDURE eliminar_equipo(
    id_equipo IN INT
)
AS
BEGIN
    BEGIN
  DELETE FROM equipos
  WHERE id_equipo = id_equipo;
  COMMIT;
 EXCEPTION
WHEN NO_DATA_FOUND THEN
            
 DBMS_OUTPUT.PUT_LINE('No se encontró el equipo con ID ' || id_equipo);
  WHEN OTHERS THEN
 ROLLBACK; 
 DBMS_OUTPUT.PUT_LINE('Error al eliminar el equipo: ' || SQLERRM);
          
   END;
END;
/




CREATE OR REPLACE PROCEDURE obtener_departamentos(
    departamentos_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    BEGIN
    OPEN departamentos_cursor FOR
     SELECT *  FROM departamentos;
  EXCEPTION
  WHEN OTHERS THEN
          
  DBMS_OUTPUT.PUT_LINE('Error al abrir el cursor: ' || SQLERRM);
            
    END;
END;
/




CREATE OR REPLACE PROCEDURE crear_departamento(
    id_departamento IN INT, nombre_departamento IN VARCHAR2
)
AS
BEGIN
   BEGIN
  INSERT INTO departamentos (id_departamento, nombre_departamento)
   VALUES (id_departamento, nombre_departamento);
 COMMIT;
 EXCEPTION
 WHEN DUP_VAL_ON_INDEX THEN
         
  DBMS_OUTPUT.PUT_LINE('Error: Ya existe un departamento con ID ' || id_departamento);
    WHEN OTHERS THEN
    ROLLBACK; 
  DBMS_OUTPUT.PUT_LINE('Error al insertar el departamento: ' || SQLERRM);
            
    END;
END;
/
